
language: php

php:
  - "7.1"
  - "7"

cache:
  directories:
    - vendor

script:
  - composer install
  - phpunit --configuration phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
